### ISSUE TITLE
Account Creation Design Patterns

### ISSUE THREAD

**Issue by reiddouglas** [SENG-350-2024-fall/Team-8#11]
Create a factory method for creating new user accounts. The factory should be given the type of user as an input and return a new user subclass (nurse, doctor) as an output.

**Comment by tej117** [comment]
Work on:
- Factory Method for Account Creation, where it is given a user type (Patient, Nurse, ...) and returns a new user subclass (Patient, Nurse, ...) as an output
- Chain of Responsibility for Account Creation Validation
- Decorator Pattern for Account Creation User Type
