### ISSUE TITLE
Expand Triage Queue Functionality

### ISSUE THREAD

**Issue by reiddouglas** [SENG-350-2024-fall/Team-8#26]
Currently, the triage queue is lacking features that could cause problems in the future. For example, there is no way to peek at the top of the queue, get the size of the queue, etc.

Go into the TriageQueueServer and TriageQueueClient and add the following functionality:
- peek
- size

Use the [java queue](https://docs.oracle.com/javase/8/docs/api/java/util/Queue.html) as a base for what to add, and what they should do. Also, if at all possible, change the function names to align with the java Queue implementation (for consistency).

**Comment by jacobarychuk** [comment]
I think we can get away without the peek method. However, I will implement the size method and use that to provide feedback about the queue size to the requesting patient and performing nurse.

**Comment by jacobarychuk** [comment]
I might be able to do this later, but in the meantime anyone can feel free to work on it.
