### ISSUE TITLE
Add Feedback to Perform Triage Page

### ISSUE THREAD

**Issue by reiddouglas** [SENG-350-2024-fall/Team-8#29]
The perform triage page needs to give more visual feedback to the user. When the queue is empty, there should be text that tells the user that they cannot get the next patient in the queue because the queue is empty. If there was a problem fetching a patient from the queue, the program should tell the user as well.

Go into PerformTriage.js and add this feedback.

**Comment by jacobarychuk** [comment]
I did this at the same time as #30 because it was helpful for testing and debugging.
