### ISSUE TITLE
Implement TriageTicket class/factory

### ISSUE THREAD

**Issue by reiddouglas** [SENG-350-2024-fall/Team-8#35]
There needs to be a way to store TriageTicket info to more easily work with it. There should be a TriageTicket class that represents the information in the database, with the appropriate setter/getter functions. The factory could take a ticketId as a parameter to do a call to a database and return the appropriate TriageTicket and also create a ticket with passed parameters (normal instantiation).

Just make it work in a reasonable way.

**Comment by jacobarychuk** [comment]
I don't think we'll have time for this. There are other features that are more essential to making the app complete.

**Comment by reiddouglas** [comment]
> I don't think we'll have time for this. There are other features that are more essential to making the app complete.

True!
